name: Check code formatting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install black

    - name: Check code formatting
      run: black --check .
